import type { Model } from "./types";

export const placeholderModels: Model[] = [
  {
    id: 1,
    title: "Geometric Desk Organizer",
    description: "A modern desk organizer with geometric patterns perfect for any workspace. Features multiple compartments and a sleek design.",
    price: 1499,
    thumbnailUrl: "https://picsum.photos/seed/organizer/400",
    modelUrl: "https://market-assets.fra1.cdn.digitaloceanspaces.com/models/desk-organizer.glb",
    creatorId: 1,
    creatorName: "DesignMaster",
    category: "Utility",
    directPrintEnabled: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    title: "Dragon Miniature",
    description: "Highly detailed dragon miniature perfect for gaming and display. Features intricate scales and dynamic pose.",
    price: 2499,
    thumbnailUrl: "https://picsum.photos/seed/dragon/400",
    modelUrl: "https://market-assets.fra1.cdn.digitaloceanspaces.com/models/dragon.glb",
    creatorId: 2,
    creatorName: "GameArtist",
    category: "Gaming",
    directPrintEnabled: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    title: "Mechanical Keyboard Case",
    description: "Custom mechanical keyboard case with modern aesthetics. Compatible with 60% PCBs.",
    price: 3999,
    thumbnailUrl: "https://picsum.photos/seed/keyboard/400",
    modelUrl: "https://market-assets.fra1.cdn.digitaloceanspaces.com/models/keyboard-case.glb",
    creatorId: 3,
    creatorName: "TechMaker",
    category: "Mechanical",
    directPrintEnabled: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 4,
    title: "Abstract Vase",
    description: "Beautiful abstract vase with unique patterns. Perfect for modern home decor.",
    price: 1999,
    thumbnailUrl: "https://picsum.photos/seed/vase/400",
    modelUrl: "https://market-assets.fra1.cdn.digitaloceanspaces.com/models/vase.glb",
    creatorId: 4,
    creatorName: "ArtisticSoul",
    category: "Art",
    directPrintEnabled: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 5,
    title: "Modular Planter System",
    description: "Stackable planter system with integrated drainage. Perfect for indoor herbs and small plants.",
    price: 2999,
    thumbnailUrl: "https://picsum.photos/seed/planter/400",
    modelUrl: "https://market-assets.fra1.cdn.digitaloceanspaces.com/models/planter.glb",
    creatorId: 5,
    creatorName: "GreenDesigns",
    category: "Utility",
    directPrintEnabled: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 6,
    title: "Sci-Fi Terrain Set",
    description: "Modular sci-fi terrain set for tabletop gaming. Includes various pieces for creating diverse layouts.",
    price: 4999,
    thumbnailUrl: "https://picsum.photos/seed/terrain/400",
    modelUrl: "https://market-assets.fra1.cdn.digitaloceanspaces.com/models/terrain.glb",
    creatorId: 6,
    creatorName: "TerrainMaster",
    category: "Gaming",
    directPrintEnabled: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 7,
    title: "Robotic Arm Kit",
    description: "DIY robotic arm kit with servo mounts. Great for learning robotics and automation.",
    price: 5999,
    thumbnailUrl: "https://picsum.photos/seed/robot/400",
    modelUrl: "https://market-assets.fra1.cdn.digitaloceanspaces.com/models/robot-arm.glb",
    creatorId: 7,
    creatorName: "RoboEngineer",
    category: "Mechanical",
    directPrintEnabled: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 8,
    title: "Geometric Wall Art",
    description: "Modern geometric wall art with customizable patterns. Makes a stunning statement piece.",
    price: 3499,
    thumbnailUrl: "https://picsum.photos/seed/wallart/400",
    modelUrl: "https://market-assets.fra1.cdn.digitaloceanspaces.com/models/wall-art.glb",
    creatorId: 8,
    creatorName: "ModernArtist",
    category: "Art",
    directPrintEnabled: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 9,
    title: "Custom Tool Holder",
    description: "Customizable tool holder with magnetic attachments. Perfect for workshop organization.",
    price: 1799,
    thumbnailUrl: "https://picsum.photos/seed/tools/400",
    modelUrl: "https://market-assets.fra1.cdn.digitaloceanspaces.com/models/tool-holder.glb",
    creatorId: 9,
    creatorName: "WorkshopPro",
    category: "Utility",
    directPrintEnabled: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 10,
    title: "Articulated Action Figure",
    description: "Fully articulated action figure with interchangeable parts. Great for customization and display.",
    price: 2999,
    thumbnailUrl: "https://picsum.photos/seed/figure/400",
    modelUrl: "https://market-assets.fra1.cdn.digitaloceanspaces.com/models/action-figure.glb",
    creatorId: 10,
    creatorName: "ToyMaker",
    category: "Art",
    directPrintEnabled: true,
    createdAt: new Date().toISOString(),
  },
];

export const categories = [
  { id: "gaming", name: "Gaming", count: 2500 },
  { id: "mechanical", name: "Mechanical", count: 1800 },
  { id: "art", name: "Art", count: 3200 },
  { id: "utility", name: "Utility", count: 1500 },
];

export const collections = [
  { id: 1, name: "Popular This Week", count: 12 },
  { id: 2, name: "Editor's Choice", count: 8 },
  { id: 3, name: "New Arrivals", count: 24 },
  { id: 4, name: "Best Sellers", count: 16 },
];
